### PR TITLE
Add docs and CI

### PR DESCRIPTION
**Pull request by tamasgal**
This is very much work in progress and targets mostly the docstrings of the `SOFA` sub-package and the CI for docs generation.

### CODE REVIEW

**Comment by tamasgal** [comment]
I created a menu structure for the SOFA sub-package and extracted all functions with a tiny shell script.

The formatting is already nice but the cross references are still missing. I also need to check all the doc strings to convert references of C functions to Julia ones.

I think it would be a good idea to rename this repository to `Astrometry.jl` to signal that it's a Julia package 🙂 We also need to set up the CI for the documentation building. Let me know if you need any help with that!

Here is a screenshot of the current docs page:

Screenshot 2024-01-09 at 10 16 04

**Comment by tamasgal** [comment]
Btw. there are still duplicate entries for a couple of functions which I will of course take care of ;) this is due to the somewhat sloppy regex I wrote to extract functions. Easy fix...

**Comment by barrettp** [comment]
Thanks Tamas. I'm at the AAS Meeting this week, so will get to this request when I return.

Many of the functions return values using NamedTuples as does the SOFA and ERFA packages. The key names of each function need to be checked to ensure they are consistent with those packages and among the functions in the package. If you have time to take a look at that, that would be great.

**Comment by tamasgal** [comment]
I looked a little bit into it and noticed that some functions are still missing (like `eraApcX` from the `erfa` package). Those will be added as well I guess?

**Comment by tamasgal** [comment]
Ah wait, I think I start to understand the naming scheme ;)

`iauAtciqn` -> `atciqn`
`eraApco13` -> `apco13`

Sorry for my ignorance but I could not figure out yet why the `iau` or `era` prefixes are omitted. It's also a bit too early yet 😁

**Comment by barrettp** [comment]
The Julia package is based on SOFA, so I guess I have missed a few additional ERFA functions. I'll take a look.

Yes, SOFA and ERFA have different function name prefixes, which, of course, I have dropped from the Julia version.

**Pull request merged**
